//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id_order { get; set; }
        public string order { get; set; }
        public int id_user { get; set; }
        public string wishes { get; set; }
        public Nullable<bool> ready { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
